### <center> Fundamentos Python </center>
#### Conceitos Basicos:
   1. **Variaveis**: São locais de memoria usadas para armazenar dados. Em python, você não precisa especificar o tipo da variavel, pois Python é uma linguagem com tipagem dinamica.

In [ ]:
nome = "Rafael"
idade = 31
altura = 1.70


2. **Tipos de dados:**
   - int: numeros inteiros. (ex: 1, 2, 100, 777)
   - float: numeros decimais. (ex: 1.14, 7.15)
   - string: vetor de caracteres, texto. (ex: \"Olá, mundo!\")
<hr>
3. **Operadores:**
    - Operadores matematicos: **+ - \* /**
    - Comparacao: **==, !=, >, <, <=, >=**
    - Logicos: ** and, or, not**
 <hr>       
4. **Condicionais:** Usados para tomada de decisão e desvio do fluxo de execução do codigo.
    - **if/else:** Executa uma determinada ação se (if) uma dada condição for verdadeira, ou não (else).
    - **match/case:** Executa um desvio de acordo com um numero limitado de opcoes.

In [ ]:
if idade >= 18:
    print("Maior de idade.")
else:
    print("Menor de idade.")
    
dia_semana = 3
match dia_semana:
    case 1:
        print("Segunda-feira")
    case 2:
        print("Terca-feira")
    case 3:
        print("Quarta-feira")
    case 4:
        print("Quinta-feira")
    case 5:
        print("Sexta-feira")
    case 6:
        print("Sabado")
    case 7:
        print("Domingo")

5. **Estrutura de repeticao(loops):** Usados para repetir uma acao diversas vezes.
    - **for:** itera sobre uma sequencia um n numero de vezes, usados em principalmente para vetores, listas, strings...
    - **while:** Executa enquanto uma dada condicao for verdadeira. 

In [ ]:
for i in range(5):
    print(i)

contador = 0
while contador < 5:
    print(contador)
    contador += 1


6. **Vetores:** Vetores são estruturas unidemensionais, capazes de armazenar diversos dados **do mesmo tipo**. No Python a maneira mais simples de criar um vetor é usando uma lista (a seguir). 

In [1]:
# Exemplo de vetor usando lista
vetor = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(vetor)
# O acesso aos alementos do vetor pode ser feito por meio do indice explicito ou uma variavel de iteracao
print(vetor[2])
# Percorrer um vetor
for item in vetor:
    print(item)
# Alterar o valor de um elemento por meio do indice
vetor[1] = 21
print(vetor[1])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
3
1
2
3
4
5
6
7
8
9
10
21


7. **Matrizes:** Uma **matriz** é uma estrutura de dados bidimensional que funciona de forma semelhando aos vetores, podendo armazenar diversos elementos do mesmo tipo e tendo acesso por meio de indices, entretanto neste caso as matrizes possuem dois indicies que indicam a posicao da linha e da coluna do vetor.

In [4]:
## Exemplo de uma matriz bidimensional
matriz = [
    [ 1, 2, 3 ],
    [ 4, 5, 6 ],
    [ 7, 8, 9 ]
]
# O acesso aos elementos de uma matriz bidimensional pode ser realizado pelos indices de linha e coluna.
print(matriz[1][2])
# Percorrer uma matriz
for linha in matriz:
    for elemento in linha:
        print(elemento, end=' ')
    print()
# Alterar elementos: Assim como em vetores, você pode modificar elementos de uma matriz.
matriz[1][1] = 17
print(matriz[1][1])

6
1 2 3 
4 5 6 
7 8 9 
17


8. Embora listas em Python funcionem bem para vetores e matrizes simples, para operacoes mais complexas, como calculos matemáticos, o uso da biblioteca **NumPy** é altamente recomendado, pois ela é mais robusta e otimizada para tais fins.

In [5]:
import numpy as np
# Exemplo de vetor usando o numpy
vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(vetor)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np
# Exemplo de matriz usando numpy
matriz = np.array([[1, 2, 3],
                   [4, 5, 6], 
                   [7, 8, 9]])
print(matriz)

Com numpy, é possivel realizar operacoes matematicas em vetores e matrizes de forma muito mais eficiente, como soma, multiplicacao, transposicao, etc.

In [8]:
import numpy as np
# Soma de matrizes usando o numpy
matriz1 = np.array([[1, 2],[3 ,4]])
matriz2 = np.array([[5, 6],[7,8]])
soma_matrizes = matriz1 + matriz2
print(soma_matrizes)
print()
# Multiplicacao de matrizes usando numpy
produto = np.dot(matriz1, matriz2)
print(produto)

[[ 6  8]
 [10 12]]

[[19 22]
 [43 50]]


#### Colecoes: Listas, Dicionarios, Tuplas, Conjuntos

1. **Listas:** Uma lista é uma colecao ordenada e mutavel (seus valores podem ser alteradores). Permite armazenar itens de tipos diferentes (numeros, strings, objetos, etc), sao bastante flexiveis e podem ser modificadas a qualquer momentos.
    - **Operacoes:** adicionar, alterar, remover. 
    - **Definidor:** [ ]

In [ ]:
# Exemplo de lista em Python
frutas = ["maçã", "laranja", "abacate", "banana"]
print(frutas)
# Acesso por indice de elemento
print(frutas[0])
# Adicionar um elemento a uma lista
frutas.append("mamão")
# Remover elemento de uma lista
frutas.remove("maçã")
print(frutas)

2. **Tuplas:** Uma tupla é similar a uma lista, mas é imutável, ou seja uma vez declarada com seus valores ela não poderá ser alterada, e portanto, não permite operacoes de adicionar, alterar ou remover. Sua melhor aplicacao é quando se quer garantir que um conjunto de dados nao seja modificado.
    - **Definidor:** ( )

In [9]:
coordenadas = ( -10.2344, 83.456 )
print(coordenadas)
# Acesso por meio de indice ao elemento da tupla
print(coordenadas[1])

(-10.2344, 83.456)
83.456


3. **Dicionarios:** O dicionario é uma estrutura do tipo chave-valor , aonde o acesso dos elementos é feito com a chave ao inves do indice para obter o valor associado a aquela chave.
    - **Definidor:** { "chave": valor }

In [10]:
aluno = { "nome": "Rafael", "idade": 31, "altura": 1.70, "nota": 9.7 }
# Acesso ao valor da nota por meio da chave
print(aluno["nota"]) 
# Adicionando uma chave-valor a estrutura
aluno["curso"] = "Sistemas de informacao"
print(aluno["curso"])
# Removendo uma chave
del aluno["altura"]
print(aluno)

9.7
Sistemas de informacao
{'nome': 'Rafael', 'idade': 31, 'nota': 9.7, 'curso': 'Sistemas de informacao'}


4. **Conjuntos (sets):** É uma colecao **nao ordenada** de elementos **unicos** . Isso significa que dentro de um conjunto não existem elementos repetidos, caso um elemento ja exista no conjunto a insercao daquele elemento repetido é simplemente descartada. É uma estrutura eficiente para verificar se um item esta presente e eleminar duplicatas.
    - **Definidor:** { }

In [ ]:
pares = { 2, 4, 6, 8, 0}
impares = { 1, 3, 5, 7, 9 }
# Operacao de uniao de conjuntos
uniao = pares | impares
interseccao = pares & impares
print(uniao)
print(interseccao)

#### Resumo das diferencas:
<hr>
    <strong>Lista:</strong> Ordenada, mutavel, permite duplicatas.<br>
    <strong>Tupla:</strong> Ordenada, imutavel, permite duplicatas.<br>
    <strong>Dicionario:</strong> Colecoes de pares chave-valor, mutavel, acesso via chave.<br>
    <strong>Conjunto:</strong> Nao ordenado, nao permite duplicatas, otimo para operacoes matematicas.<br>